name: Formatter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Setup repo
       uses: actions/checkout@v2

     - name: Format code with Prettier
       uses: creyD/prettier_action@v4.2
       with:
          commit_message: "code formatted"