# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_run:
    workflows: [pages-build-deployment]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Install Dependencies
        run: sudo npm install -g nativefier
        
      - name: Stage For Linux
        run: |
          cd ${GITHUB_WORKSPACE}
          mkdir build
          cd build
          nativefier https://meowcatheorange.github.io/Mid-Simulator/ --platform linux --arch x64 --portable --disable-context-menu --height 400 --width 700 --single-instance --zoom 1.0 --lang "en-US" --min-width 700 --min-height 400 --max-width 1400 --max-height 800
        
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "${GITHUB_WORKSPACE}/build/*"
          bodyFile: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Cleanup
        run: |
          cd ..
          rm -rf build
