# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_run:
    workflows: [pages-build-deployment]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Install Dependencies
        run: sudo npm install -g nativefier
        
      - name: Stage Overall
        run: |
          cd ${{ github.workspace }}
          zip -r Mid_Simulator.Source.zip *
          mkdir build
          mv Mid_Simulator.Source.zip build/Mid_Simulator.Source.zip
      
      - name: Stage For Linux
        run: |
          cd ${{ github.workspace }}
          cd build
          nativefier https://meowcatheorange.github.io/Mid-Simulator/ --icon "${{ github.workspace }}/sprites/jellybeanTitle.png" --name "Mid-Simulator" --platform linux --arch x64 --portable --disable-context-menu --height 400 --width 700 --single-instance --zoom 1.0 --lang "en-US" --min-width 700 --min-height 400 --max-width 1400 --max-height 800
          cd Mid-Simulator-linux-x64
          zip -r ../Mid_Simulator.Linux-amd64.zip *
        
#      - name: Stage For Windows
#        run: |
#          cd ${{ github.workspace }}/build
#          nativefier https://meowcatheorange.github.io/Mid-Simulator/ --icon "${{ github.workspace }}/sprites/jellybeanTitle.png" --name "Mid-Simulator" --platform windows --arch x64 --portable --disable-context-menu --height 400 --width 700 --single-instance --zoom 1.0 --lang "en-US" --min-width 700 --min-height 400 --max-width 1400 --max-height 800
#          ls
#          cd Mid-Simulator-win32-x64
#          zip -r ../Mid_Simulator.Windows-x86_64.zip *
#        
#      - name: Stage For Mac
#        run: |
#          cd ${{ github.workspace }}/build
#          nativefier https://meowcatheorange.github.io/Mid-Simulator/ --icon "${{ github.workspace }}/sprites/jellybeanTitle.png" --name "Mid-Simulator" --platform osx --arch x64 --portable --disable-context-menu --height 400 --width 700 --single-instance --zoom 1.0 --lang "en-US" --min-width 700 --min-height 400 --max-width 1400 --max-height 800
#          ls
#          cd Mid-Simulator-darwin-x64
#          zip -r ../Mid_Simulator.MacOSX-x86_64.zip *
#          cd ${{ github.workspace }}/build
#          nativefier https://meowcatheorange.github.io/Mid-Simulator/ --icon "${{ github.workspace }}/sprites/jellybeanTitle.png" --name "Mid-Simulator" --platform osx --arch arm64 --portable --disable-context-menu --height 400 --width 700 --single-instance --zoom 1.0 --lang "en-US" --min-width 700 --min-height 400 --max-width 1400 --max-height 800
#          ls
#          cd Mid-Simulator-darwin-arm64
#          zip -r ../Mid_Simulator.MacOSX-arm64.zip *
          
      - name: "[Debug] Check Dirs"
        run: |
          cd ${{ github.workspace }}/build
          echo "LS 1"
          ls
          cd ..
          echo "LS 2"
          ls
          cd ..
          echo "LS 3"
          ls
      
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.workspace }}/build/*.zip"
          body: "Electron build of Mid-Sim, built automatically on ${{ runner.name }} (${{ runner.os }} ${{ runner.arch }})"
          tag: "Mid-Simulator Electron Build (${{ github.sha }})"
          commit: "main"
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Cleanup
        run: |
          cd ${{ github.workspace }}
          rm -rf build
